### PR TITLE
Add frontend engineering challenge boilerplate and explanation

### PR DESCRIPTION
**Pull request by jtuppy**
Not sure if this should be added to master or stay on it's own branch, but I thought I'd create the diff for review

The challenge is essentially completing a React app that covers the majority of React development. State management, side effects, route control, list rendering, timers, async handling, event management and styling are all demonstrated in some way through the app.

Some boilerplate code is provided to get them started and build off of it. Requires them to have a good understanding of parsing a basic React app and figuring out how it works. Some tasks require them to look around the current code base to figure out how it should be done. It is still a relatively small codebase, so there is lots of room for them to improve it / refactor as they wish. They need to complete the assigned tasks, but also have lots of bonus tasks they could jump into if they finish early. It is an open ended build to make the game their own, really want to see what they do with it. Also not super easy either, requires a level or two deeper than "create a todo list".

### CODE REVIEW

**Review by rogerkirkness — APPROVED** [review]
Looks good to me. I think it's good in terms of difficulty level. I don't know enough about React to know how big an obligation this is, but it feels like a "only if we are serious" level of obligation.

**Comment by jtuppy** [comment]
I guess I should've inquired more about what stage this would be handed out. This technically could be done relatively quick with the boilerplate provided if you knew what you were doing (I might be bias tho lol). But by nature of it having a UI, it does have an open ended amount of work that could be done (design and styling sometimes take time and exploration to find what feels best). Not to mention the various ways you can extend it or make it your own. If we are looking for something that is less of an obligation to act as more of a prescreen, I can put something smaller together.

**Comment by rogerkirkness** [comment]
We could still use this as a prescreen, by asking people to recommend 3 next steps, or critique it or something. This is good for "if not for a week gauntlet, we would hire this frontend engineer" but not much short of that. And it is good, just slightly onerous.

**Comment by rogerkirkness** [comment]
@jtuppy good to merge?

**Review by rogerkirkness — APPROVED** [review]
Approving here.

**Comment by jtuppy** [comment]
Going to keep this on the `fed-challenge` branch so that it doesn't confuse the backend eng challenge... Will just send the branch specifically when sending to someone. Can always be reopened and merged if that ends up being better.

**Pull request closed without merging**
